apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-hook
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    spec:
      containers:
      - name: pre-sync-hook
        image: mtougeron/touge-debug
        command: [sleep]
        args:
          - "60"
      restartPolicy: Never
  backoffLimit: 10
